### ISSUE TITLE
Can't sync Datastore with Appsync and DynamoDB

### ISSUE THREAD

**Issue by tomrum** [dabit3/amplify-datastore-example#1]
Hello, thanks for the tutorial! Can you help me. I can't work out how to sync Datastore with Appsync and DynamoDB. I'm using cog user pools as well as api key auth. I can write to and read to datastore no problem but datastore won't sync with appsync.

Do you know what the trick is code/config?

Many Thanks in advance

**Comment by Statsministeriet** [comment]
Have you added the configs? 

`import Amplify from '@aws-amplify/core' `
`import config from './aws-exports'`
`Amplify.configure(config)`
